services:
  frontend:
    build: app #with react
    container_name: frontend
    ports:
      - 5175:5175

  backend: 
    build: back #with Nest ?
    container_name: backend
    ports:
      - 8080:8080

  # database:
  #   build: db
  #   ports:
  #     - 3200:3200